apiVersion: apps/v1
kind: Deployment
metadata:
  name: sjfiovisdngio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sjfiovisdngio
  template:
    metadata:
      labels:
        app: sjfiovisdngio
    spec:
      containers:
      - image: okteto.dev/sjfiovisdngio:latest
        name: sjfiovisdngio
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "c814ceb7-63c6-a002-1289-a3eefff54005"
        - name: Vless_Path
          value: "/vlbncgf555"
        - name: Vmess_UUID
          value: "c814ceb7-63c6-a002-1289-a3eefff54005"
        - name: Vmess_Path
          value: "/vmhjkhj666"
        - name: Share_Path
          value: "/v2link"
